# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    paths-ignore: "/EFCore.BulkExtensions.Net8.sln"
    schedule:
      interval: "monthly"
    reviewers:
      - "borisdj"
  # Maintain dependencies for .NET projects
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.Core"
    paths-ignore: "/EFCore.BulkExtensions.Core/EFCore.BulkExtensions.Core.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
  # Maintain dependencies for .NET projects
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.SqlServer"
    paths-ignore: "/EFCore.BulkExtensions.SqlServer/EFCore.BulkExtensions.SqlServer.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
  # Maintain dependencies for .NET projects
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.PostgreSql"
    paths-ignore: "/EFCore.BulkExtensions.PostgreSql/EFCore.BulkExtensions.PostgreSql.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
  # Maintain dependencies for .NET projects
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.MySql"
    paths-ignore: "/EFCore.BulkExtensions.MySql/EFCore.BulkExtensions.MySql.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
            - "borisdj"
  # Maintain dependencies for .NET projects
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.Oracle"
    paths-ignore: "/EFCore.BulkExtensions.Oracle/EFCore.BulkExtensions.Oracle.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
  # Maintain dependencies for .NET projects  
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions.Sqlite"
    paths-ignore: "/EFCore.BulkExtensions.Sqlite/EFCore.BulkExtensions.Sqlite.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
        # Maintain dependencies for .NET projects   
  - package-ecosystem: "github-actions"
    directory: "/EFCore.BulkExtensions"
    paths-ignore: "/EFCore.BulkExtensions/EFCore.BulkExtensions.Net8.csproj"
    schedule:
      interval: "monthly"
    ignore:
        - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "borisdj"
